### ISSUE TITLE
Node + Buffer?

### ISSUE THREAD

**Issue by igorescobar** [IonicaBizau/face-detectify#2]
Did you manage to make it work using node (server-side) and using `fromBuffer`?

I tried with many many different images and I never could see the detection of any faces.

```node
faceDetectify.fromBuffer(imgBuffer, 3648, 2736, (faces) => {
   console.log(faces); //  { data: [] } everytime!
});
```

**Comment by IonicaBizau** [comment]
Check out how the `fromFile` is implemented. The `buffer` comes from `getPixels`, so it may be a different kind of buffer (such as PNG, but I'm not sure): https://github.com/IonicaBizau/face-detectify/blob/7eac86cf027735f79610f5bd26db73ec4462a8f5/lib/index.js#L49-L52

**Comment by igorescobar** [comment]
@IonicaBizau 
The thing is... this is really bad documented by the `tracking.js` itself. Turned out yeah it's not any buffer that you can pass to the `tracking.js` functions. You need to use a `Uint8ClampedArray`. I don't know but if is too relevant if you are on the browser but it is quite tricky if you are on the server and not that intuitive.

Two lessons learned here.
1 - You need to convert your whatever kind of stream you are using to `Uint8ClampedArray`. Even if you pass the buffer in the wrong format `tracking.js` will tell you nothing. 
2 - You need to get right the `width` and `height` of the image. If you pass wrong dimensions to  `tracking.js` it won't give you any kind of errors it just won't detect nothing.

Thanks for your help @IonicaBizau. I hope this can help to improve the docs of `face-detectify`. Specially if you want your users to have a more "smooth" try out.
